"""create_eda_reports_table

Revision ID: 5937346024bc
Revises: 95a7f402d5eb
Create Date: 2026-09-30 16:08:05.617007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5937346024bc'
down_revision: Union[str, Sequence[str], None] = '95a7f402d5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eda_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_cleaned', sa.Boolean(), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=False),
    sa.Column('summary_statistics', sa.JSON(), nullable=False),
    sa.Column('correlation_matrix', sa.JSON(), nullable=False),
    sa.Column('distributions', sa.JSON(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eda_reports_dataset_id'), 'eda_reports', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_eda_reports_id'), 'eda_reports', ['id'], unique=False)
    op.create_index(op.f('ix_eda_reports_user_id'), 'eda_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eda_reports_user_id'), table_name='eda_reports')
    op.drop_index(op.f('ix_eda_reports_id'), table_name='eda_reports')
    op.drop_index(op.f('ix_eda_reports_dataset_id'), table_name='eda_reports')
    op.drop_table('eda_reports')
    # ### end Alembic commands ###
