"""create_clustering_models_table

Revision ID: 662417df24af
Revises: b9870abe8e28
Create Date: 2026-10-01 16:17:19.949646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662417df24af'
down_revision: Union[str, Sequence[str], None] = 'b9870abe8e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('use_cleaned', sa.Boolean(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('inertia', sa.Float(), nullable=False),
    sa.Column('silhouette_score', sa.Float(), nullable=True),
    sa.Column('cluster_centers', sa.JSON(), nullable=False),
    sa.Column('cluster_profiles', sa.JSON(), nullable=False),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=True),
    sa.Column('sample_assignments', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clustering_models_dataset_id'), 'clustering_models', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_clustering_models_id'), 'clustering_models', ['id'], unique=False)
    op.create_index(op.f('ix_clustering_models_user_id'), 'clustering_models', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clustering_models_user_id'), table_name='clustering_models')
    op.drop_index(op.f('ix_clustering_models_id'), table_name='clustering_models')
    op.drop_index(op.f('ix_clustering_models_dataset_id'), table_name='clustering_models')
    op.drop_table('clustering_models')
    # ### end Alembic commands ###
