"""create anomaly models table

Revision ID: 75ecf78d4f0d
Revises: b6684f19c504
Create Date: 2026-10-03 00:50:53.463785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ecf78d4f0d'
down_revision: Union[str, Sequence[str], None] = 'b6684f19c504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contamination', sa.Float(), nullable=False),
    sa.Column('n_estimators', sa.Integer(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('use_cleaned', sa.Boolean(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('n_anomalies', sa.Integer(), nullable=False),
    sa.Column('anomaly_percentage', sa.Float(), nullable=False),
    sa.Column('threshold_score', sa.Float(), nullable=False),
    sa.Column('score_min', sa.Float(), nullable=False),
    sa.Column('score_max', sa.Float(), nullable=False),
    sa.Column('score_mean', sa.Float(), nullable=False),
    sa.Column('summary_stats', sa.JSON(), nullable=True),
    sa.Column('anomalous_rows', sa.JSON(), nullable=True),
    sa.Column('distribution_buckets', sa.JSON(), nullable=True),
    sa.Column('scatter_points', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_models_dataset_id'), 'anomaly_models', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_anomaly_models_id'), 'anomaly_models', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_models_user_id'), 'anomaly_models', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_models_user_id'), table_name='anomaly_models')
    op.drop_index(op.f('ix_anomaly_models_id'), table_name='anomaly_models')
    op.drop_index(op.f('ix_anomaly_models_dataset_id'), table_name='anomaly_models')
    op.drop_table('anomaly_models')
    # ### end Alembic commands ###
