"""create cleaning_reports table and add cleaned fields to datasets

Revision ID: 95a7f402d5eb
Revises: 0b26457b280d
Create Date: 2026-09-29 22:40:06.427483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a7f402d5eb'
down_revision: Union[str, Sequence[str], None] = '0b26457b280d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('validation_summary', sa.JSON(), nullable=False),
    sa.Column('cleaning_summary', sa.JSON(), nullable=False),
    sa.Column('cleaned_file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_reports_dataset_id'), 'cleaning_reports', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_cleaning_reports_id'), 'cleaning_reports', ['id'], unique=False)
    op.create_index(op.f('ix_cleaning_reports_user_id'), 'cleaning_reports', ['user_id'], unique=False)
    op.add_column('datasets', sa.Column('cleaned_file_path', sa.String(length=500), nullable=True))
    op.add_column('datasets', sa.Column('has_cleaned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'has_cleaned')
    op.drop_column('datasets', 'cleaned_file_path')
    op.drop_index(op.f('ix_cleaning_reports_user_id'), table_name='cleaning_reports')
    op.drop_index(op.f('ix_cleaning_reports_id'), table_name='cleaning_reports')
    op.drop_index(op.f('ix_cleaning_reports_dataset_id'), table_name='cleaning_reports')
    op.drop_table('cleaning_reports')
    # ### end Alembic commands ###
