"""create_forecast_models_table

Revision ID: b6684f19c504
Revises: 662417df24af
Create Date: 2026-10-01 20:59:43.724944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6684f19c504'
down_revision: Union[str, Sequence[str], None] = '662417df24af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_column', sa.String(length=255), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('use_cleaned', sa.Boolean(), nullable=False),
    sa.Column('n_historical_points', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('model_parameters', sa.JSON(), nullable=False),
    sa.Column('historical_points', sa.JSON(), nullable=False),
    sa.Column('validation_points', sa.JSON(), nullable=True),
    sa.Column('forecast_points', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_models_dataset_id'), 'forecast_models', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_forecast_models_id'), 'forecast_models', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_models_user_id'), 'forecast_models', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_models_user_id'), table_name='forecast_models')
    op.drop_index(op.f('ix_forecast_models_id'), table_name='forecast_models')
    op.drop_index(op.f('ix_forecast_models_dataset_id'), table_name='forecast_models')
    op.drop_table('forecast_models')
    # ### end Alembic commands ###
