"""create_ml_jobs_and_ml_models_tables

Revision ID: b9870abe8e28
Revises: 5937346024bc
Create Date: 2026-10-01 15:09:57.431887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9870abe8e28'
down_revision: Union[str, Sequence[str], None] = '5937346024bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('feature_columns', sa.JSON(), nullable=False),
    sa.Column('test_size', sa.Float(), nullable=False),
    sa.Column('use_cleaned', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('leaderboard', sa.JSON(), nullable=True),
    sa.Column('best_model_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_jobs_dataset_id'), 'ml_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_jobs_id'), 'ml_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ml_jobs_user_id'), 'ml_jobs', ['user_id'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('target_classes', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ml_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_dataset_id'), 'ml_models', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_index(op.f('ix_ml_models_job_id'), 'ml_models', ['job_id'], unique=False)
    op.create_index(op.f('ix_ml_models_user_id'), 'ml_models', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_models_user_id'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_job_id'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_dataset_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_ml_jobs_user_id'), table_name='ml_jobs')
    op.drop_index(op.f('ix_ml_jobs_id'), table_name='ml_jobs')
    op.drop_index(op.f('ix_ml_jobs_dataset_id'), table_name='ml_jobs')
    op.drop_table('ml_jobs')
    # ### end Alembic commands ###
